include Makefile

config.h:
	echo '/* Basic config.h generated by Makefile */' > $@
	echo '#undef HAVE_CURSES' >> $@
	echo '#undef HAVE_CURSES_H' >> $@

static_samtools:  $(AOBJS) $(LZ4OBJS) libst.a 
	$(CC) $(ALL_LDFLAGS) -o samtools $(AOBJS) $(LZ4OBJS) libst.a -l:libhts.a -l:libdeflate.a -l:libbz2.a -l:liblzma.a  -l:libz.a -lm -lpthread

.PHONY: static_samtools
