name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        version: 
          - "1.21"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - name: Build binaries within docker
      run: docker build . --tag ssb --build-arg SAMTOOLS_VERSION=${{ matrix.version }}
    - name: Extract binaries
      run: docker run -i --rm --volume $(pwd):/t  ssb cp -r /target /t/static_samtools_bcftools_v${{ matrix.version }}
    - uses: actions/upload-artifact@v4
      with:
        name: static_samtools_bcftools_v${{ matrix.version }}
        path: static_samtools_bcftools_v${{ matrix.version }}
        if-no-files-found: warn
        retention-days: 90
        overwrite: true
#    - name: Push Git Tag
#      run: |
#        git config user.name "GitHub Actions"
#        git config user.email "github-actions@users.noreply.github.com"
#        git tag ${{ steps.date.outputs.date }}
#        git push origin ${{ steps.date.outputs.date }}
#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@latest
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ steps.date.outputs.date }}
#        release_name: ${{ steps.date.outputs.date }}
#        body: |
#          Static builds of Samtools & Bcftools
#        draft: false
#        prerelease: false
#    - name: GitHub Releases
#      uses: softprops/action-gh-release@v2
#      with:
#        name: ${{ steps.date.outputs.date }}
#        files: static_samtools_bcftools_v${{ matrix.version }}.tar.xz
